# Rationale:
#   - Build only master and tags
#   - Master is the most current not yet released state
#   - Tags are the only way to release a version
#   - If tag matches the latest version configured here, the floating tag
#     `:latest` will be conferred to this particular image.
#   - PR are being built and tested, but not published
#   - Concurrency is disabled; Newer jobs superseding older ones
#   - To share image between stages the intermediate product will be taged with
#     `:ci-$variant` and pushed to docker hub
sudo: false
#dist: trusty
language: bash
services:
  - docker

branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/

env:
  - FLAVOR=alpine VARIANT=php71 LATEST=0.9.0
  - FLAVOR=alpine VARIANT=php70 

before_script:
  - env | sort
  - export image="claranet/spryker-base"
  - export tag="${TRAVIS_BRANCH:-${TRAVIS_TAG}}${VARIANT:+-$VARIANT}"
  - export tagci="ci${VARIANT:+-$VARIANT}"

jobs:
  include:
    - stage: Build
      script:
        - docker build -t $image:$tagci .
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        - docker push $image:$tagci
    - stage: Test
      script:
        - docker run --rm -t $image:$tagci /entrypoint.sh build-base
    - stage: Publish
      deploy:
        provider: script
        script: ./scripts/travis-deploy.sh
        on: 
          tags: true
