# Rationale:
#   - Build only master and tags
#   - Master is the most current not yet released state
#   - Tags are the only way to release a version
#   - If tag matches the latest version configured here, the floating tag
#     `:latest` will be conferred to this particular IMAGE.
#   - PR are being built and tested, but not published
#   - Concurrency is disabled; Newer jobs superseding older ones
#   - To share IMAGE between stages the intermediate product will be taged with
#     `:ci-$variant` and pushed to docker hub
sudo: false
language: bash
services:
  - docker

branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/

env:
  - VARIANT="7.1.13-fpm-jessie" OS=debian LATEST=0.9.5
  - VARIANT="7.0.27-fpm-jessie" OS=debian 

before_script:
  - env | sort
  - export IMAGE="claranet/spryker-base"
  - export BASE_IMAGE_TAG="${VARIANT:+-$VARIANT}"
  - export BASE_IMAGE="php:${BASE_IMAGE_TAG}"
  - export VERSION="${TRAVIS_BRANCH:-${TRAVIS_TAG}}"
  - export VERSION_TAG="${VERSION}-php-${BASE_IMAGE_TAG}"
  - export tagci="ci${VARIANT:+-$VARIANT}"

script:
  - ./scripts/build.sh ${BASE_IMAGE} 
  - docker images
  - echo "[INFO] Testing IMAGE $IMAGE:$VERSION_TAG ..."
  - docker run -it --rm $IMAGE:$VERSION_TAG php -i 
  - ./scripts/travis-publish.sh
